### ISSUE TITLE
Unable to connect to self hosted qdrant instance from node.

### ISSUE THREAD

**Issue by zain-at-edensolutions** [qdrant/qdrant-js#60]
I am trying to connect to a self hosted qdrant instance using node.js but It always fails with a timeout error. Below is my connection code, I am able to connect Qdrant cloud using the below code but not a self hosted qdrant. 
My Self hosted qdrant instance works perfectly in browser and Postman but not with qdrant-js lib.
```
new QdrantClient({
    url: process.env.QDRANT_URL,
    apiKey: process.env.QDRANT_API_KEY
});
```
Here's the error I am getting:
```
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchJson (/home/zainulabd786/Specter_BE/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:113:22)
    at /home/zainulabd786/Specter_BE/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:46:26
    at handler (/home/zainulabd786/Specter_BE/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:134:16)
    at /home/zainulabd786/Specter_BE/node_modules/@qdrant/js-client-rest/dist/cjs/api-client.js:32:24
    at handler (/home/zainulabd786/Specter_BE/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:134:16)
    at fetchUrl (/home/zainulabd786/Specter_BE/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:140:22)
    at Object.fun [as getCollections] (/home/zainulabd786/Specter_BE/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:146:20)
    at QdrantClient.getCollections (/home/zainulabd786/Specter_BE/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:826:26)
    at QdrantVectorStore.ensureCollection (/home/zainulabd786/Specter_BE/node_modules/@langchain/community/dist/vectorstores/qdrant.cjs:140:26) {
  cause: AggregateError: 
      at internalConnectMultiple (node:net:1114:18)
      at internalConnectMultiple (node:net:1177:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
      at listOnTimeout (node:internal/timers:575:11)
      at processTimers (node:internal/timers:514:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error], [Error], [Error] ]
  }
}

```

Here's the versions that I am using:
node - v20.10.0
qdrant - 1.7.3
@qdrant/js-client-rest - ^1.7.0

**Comment by zain-at-edensolutions** [comment]
I was able to fix this problem by simply passing the port number. My self-hosted qdrant url had port 443 but qdrant-js uses 6333 if we don't specify the port.
