### ISSUE TITLE
cannot find module : openapi-typescript-fetch 

### ISSUE THREAD

**Issue by kwhur** [qdrant/qdrant-js#8]
Can you please check the exception below?

```

import { QdrantClient } from '@qdrant/js-client-rest';

class QdrantStorage {
  private client: QdrantClient;
  async init(): Promise<void> {
    this.client = new QdrantClient({ url: 'http://192.168.0.249:6333' });
    const result = this.client.getCollections();
    console.log(result);
  }
}

export const qdrantStorage = new QdrantStorage();

```

UncaughtException Error: Cannot find module 'C:\\Project\\app2\\platform\\server\\node_modules\\@qdrant\js-client-rest\node_modules\openapi-typescript-fetch\dist\cjs\index.js
at createEsmNotFoundErr (node:internal/modules/cjs/loader:1060:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1053:15)
    at resolveExports (node:internal/modules/cjs/loader:538:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:607:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue (C:\Users\kj.boo\AppData\Roaming\npm\node_modules\ts-node\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._resolveFilename (C:\Project\app2\platform\server\node_modules\tsconfig-paths\src\register.ts:90:36)
    at Function.Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Project\\app2\\platform\\server\\node_modules\\@qdrant\\js-client-rest\\node_modules\\openapi-typescript-fetch\\package.json'

**Comment by kwhur** [comment]
Sorry, it was a problem with my development environment, I should have gotten the answer from openapi-typescript-fetch and posted it wrong. 
I fixed it by rebuilding openapi-typescript-fetch with commonjs.
